### ISSUE TITLE
implicitly declaring library function 'isspace' with type 'int (int)'

### ISSUE THREAD

**Issue by GeroKn** [UBod/msa#17] opened 2022-04-07 14:10 UTC
Hi all,

When I try to install msa with Bioconductor, I get the following error (copying from the start of the Clustal Omega compilation):

```    Welcome to Clustal Omega - version 1.2.0 (AndreaGiacomo)

                       +NMMMMMMMMMS=
                    MMMMM?      :MMMMM8
                  IMMMMS           MMMMM,
                ~MMMMN              ,MMMMM
               =MMMMM                 MMMMM
              ?MMMMM                  +MMMMM
              MMMMMS                   MMMMM
              MMMMM                    MMMMM:
              MMMMM                    MMMMM+
              MMMMM                    MMMMM~
              MMMMM                    MMMMM
              MMMMMZ                   MMMMM
               MMMMM                  ,MMMMZ
                MMMM8                 MMMM+
                 MMMMS               MMMM,
                   MMMMO           MMMM
            ,N       SMMM        MMM8       +8
            ,M7         M+       M+        :M8
            ,MMMMMMMMMMMMI       MMMMMMMMMMMM8
            ,MMMMMMMMMMMM8       MMMMMMMMMMMM8
            ,MMMMMMMMMMMMN       MMMMMMMMMMMM8

              
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking build system type... arm-apple-darwin21.4.0
checking host system type... arm-apple-darwin21.4.0
checking whether make sets $(MAKE)... (cached) yes
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /Library/Developer/CommandLineTools/usr/bin/ld
checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 786432
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking for /Library/Developer/CommandLineTools/usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for ar... ar
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... yes
checking for gcc option to produce PIC... -fno-common -DPIC
checking if gcc PIC flag -fno-common -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin21.4.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking dependency style of gcc... (cached) gcc3
checking how to run the C preprocessor... gcc -E
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++ accepts -g... (cached) yes
checking dependency style of g++... (cached) gcc3
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /Library/Developer/CommandLineTools/usr/bin/ld
checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
checking whether the g++ linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking for g++ option to produce PIC... -fno-common -DPIC
checking if g++ PIC flag -fno-common -DPIC works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin21.4.0 dyld
checking how to hardcode library paths into programs... immediate
checking how to run the C++ preprocessor... g++ -E
checking for ANSI C header files... (cached) yes
checking assert.h usability... yes
checking assert.h presence... yes
checking for assert.h... yes
checking ctype.h usability... yes
checking ctype.h presence... yes
checking for ctype.h... yes
checking float.h usability... yes
checking float.h presence... yes
checking for float.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking math.h usability... yes
checking math.h presence... yes
checking for math.h... yes
checking for memory.h... (cached) yes
checking stdarg.h usability... yes
checking stdarg.h presence... yes
checking for stdarg.h... yes
checking stdio.h usability... yes
checking stdio.h presence... yes
checking for stdio.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking time.h usability... yes
checking time.h presence... yes
checking for time.h... yes
checking for unistd.h... (cached) yes
checking for an ANSI C-conforming const... yes
checking for size_t... yes
checking for inline... inline
checking for log in -lm... yes
checking for log2 in -lm... yes
checking whether byte ordering is bigendian... no
checking for ntohs... yes
checking for ntohl... yes
checking for ntons... no
checking for ntonl... no
checking size of unsigned short... 2
checking size of unsigned int... 4
checking size of unsigned long... 8
checking size of unsigned long long... 8
checking for stroul... no
checking for strtoull... yes
checking for ftello... yes
checking for fseeko... yes
checking for ftello64... no
checking for fseeko64... no
checking for ftell64... no
checking for fseek64... no
checking for off_t... yes
checking size of fpos_t... 8
checking if malloc debugging is wanted... no
checking whether to build with debug information... no
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating clustalo.pc
config.status: creating Doxyfile
config.status: creating src/exceptions4c/Makefile
config.status: creating src/clustal/Makefile
config.status: creating src/hhalign/Makefile
config.status: creating src/kmpp/Makefile
config.status: creating src/squid/Makefile
config.status: creating src/argtable2/Makefile
config.status: creating src/config.h
config.status: executing src/clustal-omega-config.h commands
config.status: creating src/clustal-omega-config.h - prefix CLUSTAL_OMEGA for src/config.h defines
config.status: executing depfiles commands
config.status: executing libtool commands
clang -arch arm64 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include' -I/opt/R/arm64/include    -fPIC -DHAVE_CONFIG_H -I. -DCLUSTALO -DCLUSTALO_NOFILE -DDEFAULT_FILTER=90 -I../../gc-7.6.12/include -fPIC  -falign-functions=64 -Wall -g -O2  -c exceptions4c/e4c_lite.c -o exceptions4c/e4c_lite.o
clang -arch arm64 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include' -I/opt/R/arm64/include    -fPIC -DHAVE_CONFIG_H -I. -DCLUSTALO -DCLUSTALO_NOFILE -DDEFAULT_FILTER=90 -I../../gc-7.6.12/include -fPIC  -falign-functions=64 -Wall -g -O2  -c argtable2/argtable2.c -o argtable2/argtable2.o
clang -arch arm64 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include' -I/opt/R/arm64/include    -fPIC -DHAVE_CONFIG_H -I. -DCLUSTALO -DCLUSTALO_NOFILE -DDEFAULT_FILTER=90 -I../../gc-7.6.12/include -fPIC  -falign-functions=64 -Wall -g -O2  -c argtable2/arg_end.c -o argtable2/arg_end.o
clang -arch arm64 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include' -I/opt/R/arm64/include    -fPIC -DHAVE_CONFIG_H -I. -DCLUSTALO -DCLUSTALO_NOFILE -DDEFAULT_FILTER=90 -I../../gc-7.6.12/include -fPIC  -falign-functions=64 -Wall -g -O2  -c argtable2/arg_rem.c -o argtable2/arg_rem.o
clang -arch arm64 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include' -I/opt/R/arm64/include    -fPIC -DHAVE_CONFIG_H -I. -DCLUSTALO -DCLUSTALO_NOFILE -DDEFAULT_FILTER=90 -I../../gc-7.6.12/include -fPIC  -falign-functions=64 -Wall -g -O2  -c argtable2/arg_lit.c -o argtable2/arg_lit.o
clang -arch arm64 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include' -I/opt/R/arm64/include    -fPIC -DHAVE_CONFIG_H -I. -DCLUSTALO -DCLUSTALO_NOFILE -DDEFAULT_FILTER=90 -I../../gc-7.6.12/include -fPIC  -falign-functions=64 -Wall -g -O2  -c argtable2/arg_int.c -o argtable2/arg_int.o
argtable2/arg_int.c:60:12: error: implicitly declaring library function 'isspace' with type 'int (int)' [-Werror,-Wimplicit-function-declaration]
    while (isspace(*ptr))
           ^
argtable2/arg_int.c:60:12: note: include the header <ctype.h> or explicitly provide a declaration for 'isspace'
argtable2/arg_int.c:89:8: error: implicitly declaring library function 'toupper' with type 'int (int)' [-Werror,-Wimplicit-function-declaration]
   if (toupper(*ptr++)!=toupper(X))
       ^
argtable2/arg_int.c:89:8: note: include the header <ctype.h> or explicitly provide a declaration for 'toupper'
2 errors generated.
make[2]: *** [argtable2/arg_int.o] Error 1
make[1]: *** [clustalomega] Error 1
make: *** [build_clustalomega] Error 2
ERROR: compilation failed for package ‘msa’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/msa’
```

Could you be so kind and help me out here, please? It seems to me as if there's just an inclusion missing in arg_int.c. However I'm not able to work around this.

Best regards and many thanks!
Gero

**Comment by UBod** [comment] 2022-04-08 13:17
Can you please report which platform you are using? It seems to me that -Werror is engaged. Is it possible that this switch is part of your custom compilation settings? The 'msa' package contains large amounts of third-party code, so it will never compile without warnings. So, if -Werror is set, it will never compile.

**Comment by GeroKn** [comment] 2022-04-08 13:41
Hi,

Sorry, I should have attached this directly:

```
R version 4.1.3 (2022-03-10)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.3

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] BiocManager_1.30.16 compiler_4.1.3      tools_4.1.3  
```

Any additional information I should provide? 

I'm not sure about Werror. I definitely never set it manually, wasn't even aware of this. The system is set up very freshly, so there shouldn't be any custom compilation settings in place. Plus, there are a lot of warnings before Clustal Omega, and they are not turned into errors.

Best, and many thanks for the fast reply! 
Gero

**Comment by UBod** [comment] 2022-04-08 14:11
Thanks for providing this information! Puuh, quite a new Mac system. I am afraid I cannot comment on that in more detail, since I do not have such a system at my disposal nor do I have any information about possible pitfalls on this platform. Would it, by any chance, be possible for you to work with a pre-compiled binary package as released on https://bioconductor.org/packages/3.15/bioc/html/msa.html?

**Comment by GeroKn** [comment] 2022-04-08 14:46
I've tried to use the pre-compiled package for MacOS, however there seems to be an incompatibility with the ARM architecture unfortunately:

```
> library(msa)
Loading required package: Biostrings
Loading required package: BiocGenerics

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, basename, cbind, colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find, get,
    grep, grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget, order, paste, pmax, pmax.int, pmin, pmin.int, Position,
    rank, rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply, union, unique, unsplit, which.max, which.min

Loading required package: S4Vectors
Loading required package: stats4

Attaching package: ‘S4Vectors’

The following objects are masked from ‘package:base’:

    expand.grid, I, unname

Loading required package: IRanges
Loading required package: XVector
Loading required package: GenomeInfoDb

Attaching package: ‘Biostrings’

The following object is masked from ‘package:base’:

    strsplit

Error: package or namespace load failed for ‘msa’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/msa/libs/msa.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/msa/libs/msa.so, 0x0006): tried: '/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/msa/libs/msa.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
```

**Comment by UBod** [comment] 2022-04-08 14:52
Ok, I see. Unfortunately, I feel unable to help. I suggest you post the issue on https://support.bioconductor.org/. I hope somebody has a platform like you and provide some help. If it turns out that I can make a change to the package to fix the issue, I will do it of course (as long as it does not break the package on other platforms).

**Comment by GeroKn** [comment] 2022-04-08 15:03
Ok, thanks a lot anyways! I will do as suggested, after my vacation. I might also find an alternative machine with Intel architecture to do this on...

Best,
Gero

**Comment by UBod** [comment] 2022-12-12 09:00
@GeroKn, I just wanted to let you know that a new version of `msa` has been pushed to the repo that now seems to work seemlessly with arm64. Would you please be so kind to test it on your system and let me know if the problem is solved? If so, I will close the issue. Sorry that it took so long to respond!

**Comment by UBod** [comment] 2022-12-16 08:01
As said, the new version (now 1.31.2 in the devel branch) has been updated to comply with arm64. I hope that the problem is solved. I am closing this issue.

**Closed as completed by UBod** 2022-12-16 08:01 UTC
