### ISSUE TITLE
msaPrettyPrint throws an error when verbose = FALSE

### ISSUE THREAD

**Issue by OrangeyO2** [UBod/msa#31] opened 2024-08-22 22:26 UTC
Hello

I wanted to use msaPrettyPrint using pdflatex function offered by tinytex.

When I ran the function with verbose = FALSE, I get an error

```
msaPrettyPrint(msaa, output = "pdf", verbose = FALSE)

Error in texi2dvi(texfile, quiet = !verbose, pdf = identical(output, "pdf"),  : 
  unable to run pdflatex on 'msaa.tex'
LaTeX errors:
!pdfTeX error: pdflatex.exe (file[PATH]): fflush() failed (Bad file descriptor)
 ==> Fatal error occurred, no output PDF file produced!
```

However, when verbose = TRUE, the function works and I get an alignment in a pdf file.

`msaPrettyPrint(msaa, output = "pdf", verbose = TRUE)`

Why does the function not work when verbose = FALSE?
Is there something wrong with the setup I have? (using tinytex on a Windows platform)

Thank you in advance for your help!

Package info:
tinytex_0.52
msa_1.34.0

**Comment by UBod** [comment] 2024-08-23 11:07
Thanks for reporting this one, @OrangeyO2! It turned out that the problem is caused by `tex2dvi()` if you use the arguments `quiet=TRUE` and `index=FALSE` together. I changed the interface of `msaPrettyPrint()` such that you can now explicity specify the `index` argument. So, if you wish to run `msaPrettyPrint()` with `verbose=FALSE` (which then calls `texi2dvi()` with `quiet=TRUE`), you can switch `index` to `TRUE` as a workaround. The change has already been pushed to this GitHub repo. I will push it to the BioC devel repo as version 1.37.4 as soon as a pending change from yesterday (version 1.37.3) will have been propagated.

**Comment by UBod** [comment] 2024-08-23 11:08
Since it is outside the scope of the `msa` package and since a workaround has been implement, I am now closing this issue.

**Closed as completed by UBod** 2024-08-23 11:08 UTC

**Comment by OrangeyO2** [comment] 2024-08-24 17:46
Thanks for addressing my question so quickly.
And thanks again for a wonderful package!
