### ISSUE TITLE
shadingMode does not work

### ISSUE THREAD

**Issue by zhuldyzhanzak** [UBod/msa#29] opened 2024-06-08 21:15 UTC
Hello, I am having an issue with the shadingMode function. I am trying to align two different sequences by coloring the identical regions, however the shadingMode= "identical" and shadingColors="greens" are not working. My method is method="ClustalOmega".  Can you please help to resolve it? 

[zip.zip](https://github.com/user-attachments/files/15749687/zip.zip)

**Comment by UBod** [comment] 2024-06-10 08:24
Thanks for bringing this issue to my attention, @zhuldyzhanzak! I have checked your code and the results (thanks for providing all the code). It seems that everything is ok. You selected `shadingMode="identical"` and `shadingColors="greens"`. That is exactly what is done: The former colors highlights highly conserved columns and the latter colors them in dark green. If I change the `shadingColors` parameter, the colors change. If I change the  `shadingMode` parameter (e.g. to  `"similar"`), not only the highly conserved columns are colored in dark green, but the columns with similar amino acids are colored in a lighter shade of green. If you comment refers to the two sequences pep30 and pep31, I suppose the reason why they are not colored properly is that the number of residues is below the significance threshold. Anyway, the behavior is caused by the [TeXshade package](https://ctan.org/pkg/texshade?lang=en). The `msa` package only makes the functionality of this LaTeX package available via an R interface. If it is so that this is a bug in TeXshade that has been fixed in the meantime, then please let us know (either by creating a new issue or reopening this one), and we will do our best to update `texshade.sty` in the next version of the `msa` package.

**Closed as completed by UBod** 2024-06-10 08:24 UTC
